version: "3.6"

volumes:
  app-db-data:

services:
  db:
    image: postgres:11.6
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: explorer
      POSTGRES_USER: noah
      POSTGRES_PASSWORD: password
    volumes:
      - app-db-data:/var/lib/postgresql/data
